services:

  backend-dev:
    build: 
      context: ./backend
    container_name: python-flask-app
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/VisionDB  # Pointing to the MongoDB service
    depends_on:
      - mongo-db  # Wait for the MongoDB service to start first

  mongo-db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  # For development
  frontend-dev:
    build:
      context: ./frontend
      target: development  # Use the 'development' stage
    volumes:
      - ./frontend/src:/app/src  # Mount local code for live-reloading
      - /app/node_modules  # Avoid overwriting node_modules
    ports:
      - "3000:3000"  # Expose the dev server port (e.g., for Vite)
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # For production
#   frontend-prod:
#     build:
#       context: ./frontend # Path to your frontend directory
#     ports:
#       - "80:80"           # Expose port 80 for the frontend production
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

volumes:
  mongodb_data: